resolver: lts-12.9
extra-deps:
  - aeson-1.4.1.0
  - base-orphans-0.8
  - compact-0.1.0.1
  - compactable-0.1.2.2
  - extra-1.6.13
  - foldl-1.4.0
  - free-5.1
  - lens-4.17
  - list-transformer-1.0.4
  - monad-ste-0.1.0.0
  - multiset-0.3.4
  - network-2.8.0.0
  - nf-1.0.1.0
  - planet-mitchell-0.1.0
  - prettyprinter-1.2.0.1
  - primitive-0.6.4.0
  - reactive-banana-1.2.0.0
  - semigroupoids-5.3.1
  - semilattices-0.0.0.2
  - serialise-0.2.0.0
  - tagged-0.8.6
  - termbox-0.1.0
  - termbox-banana-0.1.0
  - unagi-chan-0.4.1.0
  - unliftio-0.2.8.1
  - websockets-0.12.5.2
