resolver: lts-13.26
extra-deps:
  - aeson-1.4.4.0
  - binary-0.8.7.0
  - containers-0.6.1.1
  - primitive-0.7.0.0
  - primitive-extras-0.8
  - primitive-unlifted-0.1.1.0
  - reactive-banana-1.2.1.0
  - slave-thread-1.0.3
  - stm-containers-1.1.0.4
  - stm-hamt-1.2.0.4
  - termbox-banana-0.1.1
  - time-compat-1.9.2.2
